//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiToken
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string Token { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public System.DateTime SystemDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string RegCode { get; set; }
        public string RegName { get; set; }
        public Nullable<int> TotalDays { get; set; }
    }
}
