//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string BankID { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress2 { get; set; }
        public string BankCity { get; set; }
        public string BankState { get; set; }
        public string BankZip { get; set; }
        public string BankCountry { get; set; }
        public string BankPhone { get; set; }
        public string BankFax { get; set; }
        public string BankContactName { get; set; }
        public string BankEmail { get; set; }
        public string BankWebsite { get; set; }
        public string SwiftCode { get; set; }
        public string RoutingCode { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<double> CurrencyExchangeRate { get; set; }
        public Nullable<int> NextCheckNumber { get; set; }
        public Nullable<int> NextDepositNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> UnpostedDeposits { get; set; }
        public string GLBankAccount { get; set; }
        public string Notes { get; set; }
        public string CorrespondentBankID { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string EnteredBy { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string BankAccountTypeID { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeNo { get; set; }
        public string First_Sign { get; set; }
        public string Second_Sign { get; set; }
        public string First_Design { get; set; }
        public string Second_Design { get; set; }
        public string BranchCode { get; set; }
    }
}
