//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string Company { get; set; }
        public string Branch1 { get; set; }
        public string BranchName { get; set; }
        public string BranchManager { get; set; }
        public string BranchAddress { get; set; }
        public string ContactPerson { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string BranchAddress2 { get; set; }
        public string BranchAddress3 { get; set; }
        public string BranchCity { get; set; }
        public string BranchState { get; set; }
        public string BranchCountry { get; set; }
        public string BranchZip { get; set; }
        public string BranchPhone { get; set; }
        public string BranchEmail { get; set; }
        public string BranchFax { get; set; }
        public string BranchNotes { get; set; }
    }
}
