//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPolicy
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public Nullable<int> TaxFiscalYear { get; set; }
        public Nullable<int> TaxPeriod { get; set; }
        public Nullable<double> ReliefOnGross { get; set; }
        public Nullable<System.DateTime> CurrentPeriod { get; set; }
        public Nullable<int> AverageWrkAge { get; set; }
        public Nullable<double> WorkingHrs { get; set; }
        public string PostingCompanyID { get; set; }
        public string PostingDivisionID { get; set; }
        public string PostingDepartmentID { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public Nullable<double> WorkingDays { get; set; }
        public string TaxType { get; set; }
        public string ReliefType { get; set; }
        public Nullable<bool> Prorate { get; set; }
        public Nullable<System.DateTime> ResumptionTime { get; set; }
        public Nullable<System.DateTime> GraceTime { get; set; }
        public Nullable<System.DateTime> MidMonthDate { get; set; }
        public Nullable<System.DateTime> MidMonthPeriod { get; set; }
        public string PorationBasis { get; set; }
        public string Email { get; set; }
        public string EmailClosed { get; set; }
        public string SalaryAccount { get; set; }
        public Nullable<bool> GrossUpNonStatutoryforTax { get; set; }
        public Nullable<bool> BioSaturday { get; set; }
        public Nullable<bool> BioSunday { get; set; }
        public Nullable<int> NoofLatenessAsAbsent { get; set; }
        public string JournalBasis { get; set; }
        public Nullable<bool> PostJVasSummary { get; set; }
        public Nullable<bool> ConsolidateBillPerCostCentre { get; set; }
        public Nullable<bool> LeaveDaysWithWeekends { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> PayrollProcessed { get; set; }
        public Nullable<bool> AutoPromotion { get; set; }
        public Nullable<int> EmployeeProbationPeriod { get; set; }
        public string PAYEAccountName { get; set; }
        public string NHFAccountName { get; set; }
        public Nullable<int> PromotionInAYear { get; set; }
        public Nullable<int> DurationBeforeFirstPromotion { get; set; }
        public Nullable<bool> TaxRulesSubjectValue { get; set; }
        public string HRReportPassword { get; set; }
    }
}
