//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string Company1 { get; set; }
        public string Branch { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public string LogoUrl { get; set; }
        public string LogoFilename { get; set; }
        public string ShoppingCartURL { get; set; }
        public string ReportsDirectoryURL { get; set; }
        public string SupportDirectoryURL { get; set; }
        public string WebCRMDirectoryURL { get; set; }
        public string Notes { get; set; }
        public string CurrencyID { get; set; }
        public string BankAccount { get; set; }
        public string Terms { get; set; }
        public string FedTaxID { get; set; }
        public string StateTaxID { get; set; }
        public string VATRegistrationNumber { get; set; }
        public string VATSalesTaxID { get; set; }
        public string VATPurchaseTaxID { get; set; }
        public string VATOtherRegistrationNumber { get; set; }
        public string DefaultGLPostingDate { get; set; }
        public string DefaultSalesGLTracking { get; set; }
        public string DefaultGLPurchaseGLTracking { get; set; }
        public string DefaultSalesTaxGroup { get; set; }
        public string DefaultPurchaseTaxGroup { get; set; }
        public string DefaultInventoryCostingMethod { get; set; }
        public string AgeInvoicesBy { get; set; }
        public string AgePurchaseOrdersBy { get; set; }
        public Nullable<bool> FinanceCharge { get; set; }
        public Nullable<double> FinanceChargePercent { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseBinID { get; set; }
        public string ShippingMethod { get; set; }
        public Nullable<bool> ChargeHandling { get; set; }
        public Nullable<bool> HandlingAsPercent { get; set; }
        public Nullable<double> HandlingRate { get; set; }
        public Nullable<bool> ChargeMinimumSurcharge { get; set; }
        public Nullable<decimal> MinimumSurchargeThreshold { get; set; }
        public string GLAPAccount { get; set; }
        public string GLAPCashAccount { get; set; }
        public string GLAPInventoryAccount { get; set; }
        public string GLAPFreightAccount { get; set; }
        public string GLAPHandlingAccount { get; set; }
        public string GLAPMiscAccount { get; set; }
        public string GLAPDiscountAccount { get; set; }
        public string GLAPPrePaidAccount { get; set; }
        public string GLAPWriteOffAccount { get; set; }
        public string GLARAccount { get; set; }
        public string GLARCashAccount { get; set; }
        public string GLARSalesAccount { get; set; }
        public string GLARCOGSAccount { get; set; }
        public string GLARInventoryAccount { get; set; }
        public string GLARFreightAccount { get; set; }
        public string GLARHandlingAccount { get; set; }
        public string GLARDiscountAccount { get; set; }
        public string GLARMiscAccount { get; set; }
        public string GLARReturnAccount { get; set; }
        public string GLARWriteOffAccount { get; set; }
        public string GLFixedAccumDepreciationAccount { get; set; }
        public string GLFixedDepreciationAccount { get; set; }
        public string GLFixedAssetAccount { get; set; }
        public string GLFixedDisposalAccount { get; set; }
        public string GLBankInterestEarnedAccount { get; set; }
        public string GLBankServiceChargesAccount { get; set; }
        public string GLBankMiscWithdrawlAccount { get; set; }
        public string GLBankBankMisDepositAccount { get; set; }
        public string GLBankOtherChargesAccount { get; set; }
        public string GLRetainedEarningsAccount { get; set; }
        public string GLProfitLossAccount { get; set; }
        public string GLUnrealizedCurrencyProfitLossAccount { get; set; }
        public string GLRealizedCurrencyProfitLossAccount { get; set; }
        public string GLARFreightProfitLossAccount { get; set; }
        public string GLCurrencyGainLossAccount { get; set; }
        public string GLUnrealizedCurrencyGainLossAccount { get; set; }
        public Nullable<System.DateTime> FiscalStartDate { get; set; }
        public Nullable<System.DateTime> FiscalEndDate { get; set; }
        public Nullable<short> CurrentFiscalYear { get; set; }
        public Nullable<System.DateTime> CurrentPeriod { get; set; }
        public Nullable<System.DateTime> Period1Date { get; set; }
        public Nullable<System.DateTime> Period2Date { get; set; }
        public Nullable<System.DateTime> Period3Date { get; set; }
        public Nullable<System.DateTime> Period4Date { get; set; }
        public Nullable<System.DateTime> Period5Date { get; set; }
        public Nullable<System.DateTime> Period6Date { get; set; }
        public Nullable<System.DateTime> Period7Date { get; set; }
        public Nullable<System.DateTime> Period8Date { get; set; }
        public Nullable<System.DateTime> Period9Date { get; set; }
        public Nullable<System.DateTime> Period10Date { get; set; }
        public Nullable<System.DateTime> Period11Date { get; set; }
        public Nullable<System.DateTime> Period12Date { get; set; }
        public Nullable<System.DateTime> Period13Date { get; set; }
        public Nullable<System.DateTime> Period14Date { get; set; }
        public Nullable<bool> Period1Closed { get; set; }
        public Nullable<bool> Period2Closed { get; set; }
        public Nullable<bool> Period3Closed { get; set; }
        public Nullable<bool> Period4Closed { get; set; }
        public Nullable<bool> Period5Closed { get; set; }
        public Nullable<bool> Period6Closed { get; set; }
        public Nullable<bool> Period7Closed { get; set; }
        public Nullable<bool> Period8Closed { get; set; }
        public Nullable<bool> Period9Closed { get; set; }
        public Nullable<bool> Period10Closed { get; set; }
        public Nullable<bool> Period11Closed { get; set; }
        public Nullable<bool> Period12Closed { get; set; }
        public Nullable<bool> Period13Closed { get; set; }
        public Nullable<bool> Period14Closed { get; set; }
        public Nullable<bool> GAAPCompliant { get; set; }
        public Nullable<bool> EditGLTranssactions { get; set; }
        public Nullable<bool> EditBankTransactions { get; set; }
        public Nullable<bool> EditAPTransactions { get; set; }
        public Nullable<bool> EditARTransactions { get; set; }
        public Nullable<bool> HardClose { get; set; }
        public Nullable<bool> AuditTrail { get; set; }
        public Nullable<bool> PeriodPosting { get; set; }
        public Nullable<bool> SystemDates { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string AlternateCurrencyID { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> AllowTransactionDate { get; set; }
        public Nullable<bool> PrinterCheck { get; set; }
        public Nullable<bool> ReAuthorizePartialTransactions { get; set; }
        public string DividendAccount { get; set; }
        public string DividendPayableAccount { get; set; }
        public string RevaluationReserveAccount { get; set; }
        public string SurplusAssetRevaluationAccount { get; set; }
        public Nullable<int> PasswordAttempt { get; set; }
        public Nullable<int> PasswordDuration { get; set; }
        public Nullable<bool> EnforceProjectID { get; set; }
        public Nullable<bool> GeneratePaymentFromPurhase { get; set; }
        public Nullable<bool> CreateReceiptForDBNote { get; set; }
        public Nullable<bool> IFRS15 { get; set; }
        public Nullable<bool> AuditByPass { get; set; }
        public Nullable<bool> ApproveByPass { get; set; }
        public Nullable<bool> ReleaseByPass { get; set; }
        public string BaseURL { get; set; }
        public Nullable<bool> EnforceQualityAssuranceOnPO { get; set; }
        public Nullable<bool> bookDisbursedPayments { get; set; }
        public Nullable<bool> generateInvoicePerOrderLine { get; set; }
        public string PackID { get; set; }
        public Nullable<bool> AllowPack { get; set; }
        public Nullable<bool> IsShift { get; set; }
        public Nullable<bool> IsShowPaymentOnCashier { get; set; }
        public Nullable<bool> PrintUPC { get; set; }
        public string DefaultPrinterName { get; set; }
        public Nullable<bool> IsSwitchCategoryProduct { get; set; }
        public Nullable<bool> IsFullScreen { get; set; }
        public Nullable<bool> IsShowTable { get; set; }
        public Nullable<double> MarkUpCost { get; set; }
        public Nullable<bool> MarkUp { get; set; }
        public string MaterialUsageAccount { get; set; }
        public string SmtpHost { get; set; }
        public string SmtpUsername { get; set; }
        public string SmtpPassword { get; set; }
        public string SmtpPort { get; set; }
    }
}
