//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyType
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string CurrencyID { get; set; }
        public string CurrencyType1 { get; set; }
        public string CurrenycySymbol { get; set; }
        public Nullable<double> CurrencyExchangeRate { get; set; }
        public Nullable<System.DateTime> CurrencyRateLastUpdate { get; set; }
        public Nullable<int> CurrencyPrecision { get; set; }
        public string MajorUnits { get; set; }
        public string MinorUnits { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
    }
}
