//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaf
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string LeaveType { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string PayTypeID { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public Nullable<int> OutLeaveDays { get; set; }
        public Nullable<double> ActualAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public Nullable<bool> Cleared { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> Posted { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<int> PriorLeaveDays { get; set; }
        public int LeaveID { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public string EmployeeName { get; set; }
        public string SSApprovedBy { get; set; }
        public Nullable<bool> ExecutivePermision { get; set; }
        public string ExecutivePermisionBy { get; set; }
        public Nullable<System.DateTime> ExecutiveApproveDate { get; set; }
        public string ExecutivePermisionName { get; set; }
        public string Transtype { get; set; }
        public string NotesB { get; set; }
        public Nullable<bool> Audited { get; set; }
        public string AuditedBy { get; set; }
        public Nullable<System.DateTime> AuditedDate { get; set; }
        public string ApprovedByName { get; set; }
        public string PostedByName { get; set; }
        public Nullable<System.DateTime> ResumptionDate { get; set; }
        public string PhoneNo { get; set; }
    }
}
