//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsLine
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string DepartmentID { get; set; }
        public string GroupID { get; set; }
        public decimal GroupDetailID { get; set; }
        public string PayTypeID { get; set; }
        public string BasisID { get; set; }
        public string AttrID { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public string TaxGroupID { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public Nullable<bool> ActiveYN { get; set; }
        public string GLAccountNumber { get; set; }
    }
}
