//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string LeaveTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Payable { get; set; }
        public Nullable<bool> OnPayroll { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public Nullable<bool> CalcOnLeaveDays { get; set; }
        public Nullable<short> MaximumDays { get; set; }
        public string MaxWorkingdays { get; set; }
        public string UsagePeriod { get; set; }
        public string LeaveGender { get; set; }
        public string PayTypeID { get; set; }
    }
}
