//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu
    {
        public int MenuId { get; set; }
        public string Icon { get; set; }
        public string Name { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> MainMenuId { get; set; }
        public Nullable<int> OrderingId { get; set; }
    }
}
