//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayElementsView
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string EmployeeID { get; set; }
        public string PayTypeID { get; set; }
        public string AttrID { get; set; }
        public Nullable<double> VALUE { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public Nullable<double> PayTypeBalance { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> PensionDate { get; set; }
        public string PayTypeDescription { get; set; }
        public Nullable<bool> ActiveYN { get; set; }
        public Nullable<bool> OnPayroll { get; set; }
    }
}
