//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string PayTypeID { get; set; }
        public string PayTypeDescription { get; set; }
        public string GLAccountNumber { get; set; }
        public string AttrDescription { get; set; }
        public string OperatorID { get; set; }
        public double ConversionFactor { get; set; }
        public string TotalAmount { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string StatusID { get; set; }
        public Nullable<bool> PayTypeDefault { get; set; }
        public Nullable<double> EmployeePercent { get; set; }
        public Nullable<bool> Zerorise { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Accrued { get; set; }
        public Nullable<double> EmployerPercent { get; set; }
        public string PayTypeGLAccountNumber { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public string GLAccountNumber1 { get; set; }
        public Nullable<bool> Prorate { get; set; }
        public Nullable<bool> IgnoreHourlyRate { get; set; }
        public Nullable<bool> BillingItem { get; set; }
        public Nullable<bool> ShowBalanceOnSlip { get; set; }
    }
}
