//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollPeriod
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public System.DateTime Period { get; set; }
        public string Description { get; set; }
        public string GeneratedBy { get; set; }
        public Nullable<bool> Generated { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string AuditedBy { get; set; }
        public Nullable<bool> Audited { get; set; }
        public Nullable<System.DateTime> AuditedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string AuditComment { get; set; }
        public Nullable<double> TotalGrossPay { get; set; }
        public Nullable<double> TotalGrossDeduction { get; set; }
        public Nullable<double> TotalNetPay { get; set; }
        public string BranchCode { get; set; }
    }
}
