//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollPeriodLine
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public System.DateTime Period { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<double> NetPay { get; set; }
        public Nullable<double> GrossDeduction { get; set; }
        public Nullable<double> GrossPay { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string EmployeeName { get; set; }
        public string BranchCode { get; set; }
    }
}
