//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayTypesLine
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string DepartmentID { get; set; }
        public string PayTypeID { get; set; }
        public string PayTypeDetailID { get; set; }
        public decimal PayTypeDetailInc { get; set; }
        public string EmployeePercent { get; set; }
        public string EmployerPercent { get; set; }
        public string OperatorID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
    }
}
