//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFA
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string PFAID { get; set; }
        public string PFADescription { get; set; }
        public string PFAAddress { get; set; }
        public string PFAPhone { get; set; }
        public string PFAEmail { get; set; }
        public string PFAContact { get; set; }
        public string ReceivingBank { get; set; }
        public string ReceivingAcctNo { get; set; }
        public string PFALogo { get; set; }
        public string PFAFreeCode { get; set; }
        public string InstrumentNumber { get; set; }
        public string EmployerCode { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string BranchCode { get; set; }
    }
}
