//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string LockedBy { get; set; }
        public Nullable<bool> LockTS { get; set; }
    }
}
