//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardRelief
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public int FiscalYear { get; set; }
        public double ReliefRate { get; set; }
        public Nullable<double> PersonalAllowance { get; set; }
        public Nullable<double> DisabilityAllowance { get; set; }
        public Nullable<double> ChildAllowance { get; set; }
        public Nullable<double> DependentAllowance { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public Nullable<double> MinimumTaxAmount { get; set; }
        public Nullable<double> TaxGrossPercent { get; set; }
        public Nullable<bool> AllStaffRelief { get; set; }
        public string BranchCode { get; set; }
    }
}
