//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxTableLine
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public int FiscalYear { get; set; }
        public string StateID { get; set; }
        public double BandWidth { get; set; }
        public double LowerLimit { get; set; }
        public double UpperLimit { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> FixedValue { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string CurrencyID { get; set; }
    }
}
