//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string OldPassword { get; set; }
        public Nullable<System.DateTime> PasswordChangedDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string UserGroupID { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ADUsername { get; set; }
        public Nullable<bool> PasswordExpires { get; set; }
        public Nullable<System.DateTime> PasswordExpiresDate { get; set; }
        public string Signature { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
    }
}
