//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearEmployeePayAnalysi
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeTypeID { get; set; }
        public string EmployeeUserName { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeePasswordOld { get; set; }
        public Nullable<System.DateTime> EmployeePasswordDate { get; set; }
        public Nullable<bool> EmployeePasswordExpires { get; set; }
        public Nullable<int> EmployeePasswordExpiresDate { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<bool> ActiveYN { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public string EmployeeCity { get; set; }
        public string EmployeeState { get; set; }
        public string EmployeeZip { get; set; }
        public string EmployeeCountry { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeeFax { get; set; }
        public string EmployeeSSNumber { get; set; }
        public string EmployeeEmailAddress { get; set; }
        public string EmployeeDepartmentID { get; set; }
        public string PictureURL { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Commissionable { get; set; }
        public Nullable<double> CommissionPerc { get; set; }
        public string CommissionCalcMethod { get; set; }
        public string EmployeeManager { get; set; }
        public string EmployeeRegionID { get; set; }
        public string EmployeeSourceID { get; set; }
        public string EmployeeIndustryID { get; set; }
        public string Notes { get; set; }
        public string NextOfKinName { get; set; }
        public string NextOfKinNumber { get; set; }
        public Nullable<decimal> MonthToDateGross { get; set; }
        public Nullable<decimal> MonthToDateFICA { get; set; }
        public Nullable<decimal> MonthToDateFederal { get; set; }
        public Nullable<decimal> MonthToDateState { get; set; }
        public Nullable<decimal> MonthToDateLocal { get; set; }
        public Nullable<decimal> MonthToDateOther { get; set; }
        public Nullable<decimal> QuarterToDateGross { get; set; }
        public Nullable<decimal> QuarterToDateFICA { get; set; }
        public Nullable<decimal> QuarterToDateFederal { get; set; }
        public Nullable<decimal> QuarterToDateState { get; set; }
        public Nullable<decimal> QuarterToDateLocal { get; set; }
        public Nullable<decimal> QuarterToDateOther { get; set; }
        public Nullable<decimal> YearToDateGross { get; set; }
        public Nullable<decimal> YearToDateFICA { get; set; }
        public Nullable<decimal> YearToDateFederal { get; set; }
        public Nullable<decimal> YearToDateState { get; set; }
        public Nullable<decimal> YearToDateLocal { get; set; }
        public Nullable<decimal> YearToDateOther { get; set; }
        public string EmployeeCounty { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string EnteredBy { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string DocumentID { get; set; }
        public string EmployeeFirstname { get; set; }
        public string EmployeeOthername { get; set; }
        public string TitleID { get; set; }
        public string EmployeeHomephone { get; set; }
        public string EmployeeOfficephone { get; set; }
        public string EmployeeOfficeExt { get; set; }
        public string EmployeeAddress3 { get; set; }
        public string EmployeeAddress4 { get; set; }
        public string EmployeeAddress5 { get; set; }
        public string PFAID { get; set; }
        public string BankID { get; set; }
        public string DesignationID { get; set; }
        public string EmployeeManagerID { get; set; }
        public string ContractTypeID { get; set; }
        public string CurrencyID { get; set; }
        public string EmployeeMaidenName { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public string PFANo { get; set; }
        public string GenderID { get; set; }
        public string StatusID { get; set; }
        public string StateID { get; set; }
        public string NationalityID { get; set; }
        public string LanguageID { get; set; }
        public string GradeID { get; set; }
        public string AccountNo { get; set; }
        public string GroupID { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public string JobClassID { get; set; }
        public string Location { get; set; }
        public string CostCenter { get; set; }
        public Nullable<double> BaseValue { get; set; }
        public Nullable<double> MonthlyTax { get; set; }
        public Nullable<double> YearToDateTax { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> PromotionDate { get; set; }
        public string WorkedDays { get; set; }
        public Nullable<System.DateTime> LastPayDate { get; set; }
        public Nullable<System.DateTime> PensionDate { get; set; }
        public string StatePAYE { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string GroupDescription { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<bool> Cleared { get; set; }
        public string EmployeeActivityTypeID { get; set; }
        public Nullable<bool> ProvideForTax { get; set; }
        public string PayrollEmployeeUserGroupID { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public Nullable<bool> SalaryPaid { get; set; }
        public Nullable<double> CurrencyExchangeRate { get; set; }
        public string EmployeePostalAddress { get; set; }
        public string LGA { get; set; }
        public string GeoArea { get; set; }
        public string BnkSortCode { get; set; }
        public string Tax_Number { get; set; }
    }
}
