//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearPayFileTaxLine
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public Nullable<double> AnnualGross { get; set; }
        public Nullable<double> TotalFreepay { get; set; }
        public Nullable<double> TotalTaxableIncome { get; set; }
        public Nullable<double> AnnualTaxAmount { get; set; }
        public Nullable<double> MonthlyTaxAmount { get; set; }
        public Nullable<double> TaxRefund { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockTS { get; set; }
        public string BranchCode { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<double> CurrencyExchangeRate { get; set; }
    }
}
